- name: Installs BorgBackup Client
  hosts: backup
  become: yes
  tasks:
    - name: promt
      pause:
        prompt: "heb je eerst de backup server ingesteld & SSH-Keygen en ssh-copy-ID gedaan?"

    - name: debug
      debug:
        msg: naam {{ inventory_hostname }}

    - name: yum install epel-release
      yum:
        name: epel-release
        state: present

    - name: yum install Borg backup
      yum:
        name: borgbackup
        state: present

    - name: yum install python
      yum:
        name:
          - python
          - python-pip
        state: present

    - name: pip install borg
      command: sudo pip3 install --upgrade borgmatic

    - name: pip install borg
      command: echo export 'PATH="$PATH:/root/.local/bin"' >> ~/.bashrc

    - name: pip install borg
      shell: source ~/.bashrc

    - name:
      copy:
        src: /home/ansible/files/borg/{{ inventory_hostname }}.yaml
        dest: /etc/borgmatic/config.yaml
        mode: "0755"
        owner: root
        group: root
