- name: This sets up an zammad docker container
  hosts: docker
  become: yes
  tasks:
    - name: make directory
      file:
        path: /home/ansible/ownCloud
        state: directory
        mode: "0755"

    - name: get files
      get_url:
        url: https://raw.githubusercontent.com/owncloud/docs/master/modules/admin_manual/examples/installation/docker/docker-compose.yml
        dest: /home/ansible/ownCloud/docker-compose.yml
    - name: set env
      blockinfile:
        path: /home/ansible/ownCloud/.env
        create: yes
        block: |
          OWNCLOUD_VERSION=10.4
          OWNCLOUD_DOMAIN=localhost
          ADMIN_USERNAME=admin
          ADMIN_PASSWORD=password
          HTTP_PORT=8080

    - name:
      command: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
      ignore_errors: yes

    - name: start script
      shell: "cd ownCloud; docker-compose up -d"
